rules:
  default:
    merge_strategy:
    method: merge
    protection:
      required_pull_request_reviews:
        required_approving_review_count: null
      required_status_checks:
        contexts: []